// <auto-generated />
using System;
using Anderson_Gomez_Ap1_p2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Anderson_Gomez_Ap1_p2.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220317202810_Producto")]
    partial class Producto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Anderson_Gomez_Ap1_p2.Entidades.Frutos", b =>
                {
                    b.Property<int>("FrutosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Peso")
                        .HasColumnType("INTEGER");

                    b.HasKey("FrutosId");

                    b.ToTable("Frutos");
                });

            modelBuilder.Entity("Anderson_Gomez_Ap1_p2.Entidades.FrutosDetalle", b =>
                {
                    b.Property<int>("DetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrutosId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Producto")
                        .HasColumnType("TEXT");

                    b.HasKey("DetallesId");

                    b.HasIndex("FrutosId");

                    b.ToTable("FrutosDetalle");
                });

            modelBuilder.Entity("Anderson_Gomez_Ap1_p2.Entidades.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Costo")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCaducidad")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ganancia")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Gramos")
                        .HasColumnType("REAL");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorInventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Anderson_Gomez_Ap1_p2.Entidades.ProductosDetalle", b =>
                {
                    b.Property<int>("DetallesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cantidad")
                        .HasColumnType("REAL");

                    b.Property<string>("DescripcionDetalle")
                        .HasColumnType("TEXT");

                    b.Property<int>("Empaque")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<string>("Presentacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetallesId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosDetalles");
                });

            modelBuilder.Entity("Anderson_Gomez_Ap1_p2.Entidades.FrutosDetalle", b =>
                {
                    b.HasOne("Anderson_Gomez_Ap1_p2.Entidades.Frutos", null)
                        .WithMany("FrutosDetalles")
                        .HasForeignKey("FrutosId");
                });

            modelBuilder.Entity("Anderson_Gomez_Ap1_p2.Entidades.ProductosDetalle", b =>
                {
                    b.HasOne("Anderson_Gomez_Ap1_p2.Entidades.Productos", null)
                        .WithMany("ProductosDetalle")
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("Anderson_Gomez_Ap1_p2.Entidades.Frutos", b =>
                {
                    b.Navigation("FrutosDetalles");
                });

            modelBuilder.Entity("Anderson_Gomez_Ap1_p2.Entidades.Productos", b =>
                {
                    b.Navigation("ProductosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
